server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Любой запрос роутим в index.html (для React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
